# Generated by Django 5.2.11 on 2026-02-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_documento_comentario_documento_estado_proveedor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='requiere_vencimiento',
            field=models.BooleanField(default=True, verbose_name='Requiere Vencimiento'),
        ),
    ]
