# Generated by Django 5.2.11 on 2026-02-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_tipodocumento_requiere_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
