# Generated by Django 5.2.11 on 2026-02-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_documento_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='enviado_a_proveedor',
            field=models.BooleanField(default=False, verbose_name='Enviado al Proveedor'),
        ),
    ]
