# Generated by Django 5.2.11 on 2026-02-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_documento_enviado_a_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='subido_por',
            field=models.CharField(choices=[('admin', 'Administración'), ('proveedor', 'Proveedor')], default='proveedor', max_length=20, verbose_name='Subido por'),
        ),
    ]
